# Which agentic-lib workflow schedule should be used?
schedule: schedule-4

# Mapping for from symbolic keys to filepaths for access by agentic-lib workflows with limits and access permissions
paths:
  # Filepaths for elaborator workflows
  missionFilepath:
    path: 'MISSION.md'
  librarySourcesFilepath:
    path: 'SOURCES.md'
    permissions: []
    limit: 0
  libraryDocumentsPath:
    path: 'library/'
    permissions: []
    limit: 0
  featuresPath:
    path: 'features/'
    permissions: [ 'write' ]
    limit: 2

  # Filepaths for engineer workflows
  contributingFilepath:
    path: 'CONTRIBUTING.md'
  targetTestsPath:
    path: 'tests/unit/'
    permissions: [ 'write' ]
  otherTestsPaths:
    paths: []
  targetSourcePath:
    path: 'src/lib/'
    permissions: [ 'write' ]
  otherSourcePaths:
    paths: []
  dependenciesFilepath:
    path: 'package.json'
    permissions: [ 'write' ]
  documentationPath:
    path: 'docs/'
    permissions: [ 'write' ]

  # Filepaths for maintainer workflows
  formattingFilepath:
    path: '.prettierrc'
  lintingFilepath:
    path: 'eslint.config.js'
  readmeFilepath:
    path: 'README.md'
    permissions: [ 'write' ]

# Execution commands
buildScript: 'npm run build'
testScript: 'npm test'
mainScript: 'npm run start'

# How many issues should be available to be picked up?
featureDevelopmentIssuesWipLimit: 2
maintenanceIssuesWipLimit: 1

# How many attempts should be made to work on an issue?
attemptsPerBranch: 2
attemptsPerIssue: 1

# Web publishing
docRoot: 'public'

# Sandbox configuration
#sandbox:
#  sandboxReset: 'true'
#  sandboxPath: 'sandbox'

# Repository seeding
seeding:
  repositoryReseed: 'true'
  sourcePath: 'seeds/zero-main.js'
  testsPath: 'seeds/zero-tests.js'
  dependenciesFilepath: 'seeds/zero-package.json'
  readmeFilepath: 'seeds/zero-README.md'

# The intention is associated with the bot's discussion thread.
intentionBot:
  intentionFilepath: 'intentïon.md'
